### ISSUE TITLE
Parentheses matching algorithm doesn't work right if literal strings contain parentheses

### ISSUE THREAD

**Issue by winteryoung** [atom/language-clojure#42] opened 2016-03-28 05:48 UTC
```clojure
(foo "bar)")
```

Try the above example.

**Comment by 50Wliu** [comment] 2016-03-28 13:19
This looks like a duplicate of atom/bracket-matcher#78 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-28 13:19 UTC
